### ISSUE TITLE
Getting lots of open sockets leading to resource starvation

### ISSUE THREAD

**Issue by elafargue** [PolaricServer/webapp#12] opened 2015-11-06 16:30 UTC
I noticed that in many occasions, the web app ends up opening dozens of http sockets, leading the browser to issue "waiting for available sockets" messages and waiting for about 2 minutes before updating again. Is this something you have seen on other installations? Is there an Apache setting that needs to be modified to avoid this?

This might actually be connected to aprsd who leaves connections open waiting for a certain amount of time before returning the data. The front-end should be the one making sure there is a certain interval between regular requests, and the back-end should just return the data immediately, imho. Browsers don't seem to cope very well with http sockets that remain open with no data for a long time...

**Comment by ohanssen** [comment] 2015-12-16 20:36
This is a tricky one. The back-end waits for a change to happen within the area of interest, but waits at most 2 minutes. Simple polling from the client would be quite inefficient. I have seen cases where many connections are open but this is a while ago. I haven't seen resource starvation. 

In the client code there is a timeout on calls where the call is cancelled after 2.5 minutes and the browser re-loads if this fails. At least this is the intended behaviour.

**Comment by ohanssen** [comment] 2015-12-16 23:01
Blocking HTTP requests like this is complex and not very efficient. A better solution would be to use the new web-socket protocol.

**Comment by ohanssen** [comment] 2015-12-20 21:19
I have now opened a branch for moving to web-sockets.

**Comment by elafargue** [comment] 2015-12-20 22:45
That's great, thanks Øyvind,

Ed

(phone)

**Comment by ohanssen** [comment] 2016-03-10 23:58
Implemented and merged. Testing results are promising.

**Closed** 2016-03-10 23:59 UTC
